### ISSUE TITLE
Is there some way to port this over to the playground?

### ISSUE THREAD

**Issue by ANONYMOUSEJR** [4as/ChatGPT-DeMod#11]
There is a moderation endpoint there just like with chatgpt so i was wondering what could be done so that it also works there.

[https://platform.openai.com/playground/]

**Comment by 4as** [comment]
Currently I can't say for certain if it's truly doable. I already used up my free trial tokens and I don't really want to spend my own money to implement this, so even if it's possible it will have to wait for now.

**Comment by pukkandan** [comment]
My free tokens have expired too, but last time I used it, there was no moderation check in playground. @ANONYMOUSEJR, could you show us what you are seeing?

**Comment by ANONYMOUSEJR** [comment]
@pukkandan Ah, sorry.
I was still new and didn't know much.
You're right there is no moderation i just forgot to close this issue...
I'll do so now.
