### ISSUE TITLE
Is this still working? I see it intercepting in console but its getting blocked by chatgpt still

### ISSUE THREAD

**Issue by matthewmoura** [4as/ChatGPT-DeMod#12]

**Comment by CATKit8** [comment]
Well, hello, at least in my case, the DeMod button doesn't appear and the "This content might violate our content policy" message appear instantly after I make ChatGPT answer something that goes against their content policy. This is the first time I've used this script. I utilized a Bromite Browser fork in Android.

**Comment by ArvonSCP** [comment]
> 

had the same problem and was able to fix it, you simply have to refresh your page, it's that easy

**Comment by 4as** [comment]
> Well, hello, at least in my case, the DeMod button doesn't appear and the "This content might violate our content policy" message appear instantly after I make ChatGPT answer something that goes against their content policy. This is the first time I've used this script. I utilized a Bromite Browser fork in Android.

I've checked what was going on in Bromite and I think I've fixed it. If you download the latest version of the script it should now work without issues.

**Comment by CATKit8** [comment]
@ArvonSCP even after refreshing it three times it didn't work. Still, thank you so much for your reply.

@4as it finally worked, thank you so much!
