### ISSUE TITLE
DeMod not working in Safari 14, Error: Object.hasOwn is not a function. and won't load conversations.

### ISSUE THREAD

**Issue by ProgrammerG4** [4as/ChatGPT-DeMod#16]
Hi There.

Firstly I just wanted to thank you for all your hard work.
This isn't a major major issue, as I can use Firefox instead of Safari, but I thought I would bring it up in case it's an easy fix, and in case others might be having the same issue.

I had no issues with Safari 14 and the previous 1.6 DeMod, but the current 1.7 DeMod I get the error message: "Object.hasOwn is not a function. (In 'Object.hasOwn(arg[1], 'body')', 'Object.hasOwn' is undefined)", when I type anything into ChatGPT with DeMod enabled, ChatGPT works fine with it DeMod disabled in Tampermonkey.
And when trying to load a previous conversation, I get the error Unable to load conversation e82519ab-e572-4d4c-8bf9-b99d7e6529c8.

Hopefully it's an easy fix, but if not, it's not the end of the world.

Thank you!

**Comment by 4as** [comment]
Since I don't have access to Safari 14 I sort of have to fix this blindly. Could you install DeMod from this link: [4as.pl/other/demod.user.js](https://4as.pl/other/demod.user.js) and tell me if this version fixes the problem? If yes then I will push an official update.

**Comment by ProgrammerG4** [comment]
Thank you. Yes, I should probably upgrade from Mojave, but I still have some legacy 32bit stuff that's keeping me from updating.
It works perfectly! Thank you so much for that!
