### ISSUE TITLE
WARNING: Don't use "share" option

### ISSUE THREAD

**Issue by superdemouser** [4as/ChatGPT-DeMod#18]
There is a new feature to share each conversation directly from ChatGPT UI. 

DON'T USE IT, IT WILL FLAG ALL YOUR MESSAGES.

Once you start the share UI the whole conversation, each input and response, is passed trough the moderation API and flagging all messages as warnings or violations. 

@4as Is there a way to skip this moderation and share the conversations? Or at least make the Share option disabled when the DeMod is on?

Thanks!

**Comment by 4as** [comment]
Sharing has the same root problem as this issue
https://github.com/4as/ChatGPT-DeMod/issues/17
I'm currently in process of exploring options to create workarounds for all of those issues.

**Comment by 4as** [comment]
I just pushed on update that prevents the "share" functionality from working.
