### ISSUE TITLE
Watch out! [Content Policy Violation] Mail

### ISSUE THREAD

**Issue by Lefioty** [4as/ChatGPT-DeMod#19]
Guys! Watch out!

I received [Content Policy Violation] Mails in each of my 2 accounts since July, 1 while using GPT4 for NSFW creations **with DeMod codes on all the time**.

**My recent usage is like this:**
- Countdown each 3hrs and sending requests as many times and as quick posibile. (about 1hr for running out all 25 messages quota)
- The first account were **sending every 25 requests per 3hr, 5~ 6 rows a day (125 ~150 requests total per day)**.
- I stopped renewing subscription of the first account since July 1 after receiving the [Content Policy Violation] Mail.
- I started the Second account after that, and using more cautiously which were **sending 20~ 24 requests per 3hr, 1~ 3 rows per day**.
- I tried to avoid pressing the [⏩ (Continue)] Button if it shows up, but I pressed it maybe 2 times or some more accidentally.
- And I still got [Content Policy Violation] Mail for the second account just yesterday (July 4).
- **I didn't got any of my messages flagged in the client side UI, which means DeMod codes should be working.**

**My guesses of what triggers the system flagging my account:**
- Intense usage in short period? 
- Pressing [⏩ (Continue)] Button may trigger the server side flagging my accounts?

I don't know what actually triggers the system flagging. And I will keep report the following situations after further usages more cautiously (Trying not to waste the money spent for my second account).

Good luck, I hope you guys can keep enjoy the fun!

Thanks @4as for creating such good tool for us.

**Comment by 4as** [comment]
I already talked with someone who also got warning emails and I'm currently waiting for them to report back to me, as it appears to be an issue with other extensions unrelated to DeMod.  
Please open your browser's console (F12 on Chrome and Firefox) and see if you get any errors when you send messages to ChatGPT. Anything similar to "Failed to fetch" or "ERR_BLOCKED_BY_USER" is very bad news. OpenAI doesn't like when people are messing with the flow of server calls. When I first started developing DeMod I got similar emails when I didn't know what I was doing.
Currently I'm using DeMod daily for NSFW stuff and I'm yet to receive an warning email. The difference between me and the user that also got warning emails is that they were getting a lot of errors in the console. Which is why I'm waiting for them to report back to me, if they managed to fix them.  
If you or anyone else is also getting warning emails, please see if you're using anything that could be blocking calls to the moderation endpoint - extensions, anti-virus, ad blockers, other tampermonkey scripts - and disable them, leaving only DeMod. Then see if you still will be getting warning emails. When DeMod is working you shouldn't be getting any errors in the console when you send a message (there could be a one or two when you enter the site though).

**Comment by Lefioty** [comment]
Got it! 
I've removed Firefox Extensions: AdBlocker 
And I also removed the rest of extensions and user scripts besides tampermonkey and DeMod just in case.

Thanks for the help! 👍

**Comment by Lefioty** [comment]
Got it!
I've removed Firefox Extensions: AdBlocker
And I also removed the rest of extensions and user scripts besides tampermonkey and DeMod just in case.

Thanks for the help! 👍

**Comment by 4as** [comment]
I'm going to leave the issue on open until I have confirmation that the source of warning emails is indeed in other extensions interfering, rather than DeMod not offering a proper protection from moderation checks.
If people are getting warnings, or even bans, despite having DeMod working perfectly, then it means the script is no longer working, and should not be up for download.

**Comment by Vicarious789** [comment]
I don't know if this is relevant but I logged into a secondary account that I had not used for over a month and instantly got a warning email on it. There was only one conversation in the history, which triggered no moderation or issues at the time I last used it. I didn't even click the conversation or send any messages. I also got warnings on the main account I use, I think four at this point but that other one stood out.

**Comment by 4as** [comment]
Which is why I think the issue with warnings is not related to DeMod. When you log into your secondary account, could you take a look at your console and post it here? I suspect it's the communication with the server that is being disrupted and causing warnings to appear.

**Comment by Lefioty** [comment]
Hello, @4as :

I just heard about [Mnemosyne](https://github.com/BruceMacD/mnemosyne) which looks fun and says it's "long term memory for ChatGPT".

I wonder if it's possible utilizing Mnemosyne in designated environment for DeMod would trigger warning mail or not?

Thanks. 🙂

**Comment by Lefioty** [comment]
Ok, I just got another warning mail while I was translating some NSFW subtitle file (*.srt). 

I was experiencing looping output issu like this: 
1. Requesting translation of subtitles from line 1 to 35.
2. The initail output stopped at half of line 22, and show up [⏩] Continue Botton
3. Than it continute reapeated output from line 1 of the subtitiles, or sometime it outputed reject messages.

I'm pretty sure the my Firefox is only installed tampermonkey extension and DeMod script only this time.

And I got an Error message in the F12 console and it's about the same time got the warning mail:
"UserError: You have sent too many messages to the model. Please try again later."

I requested less line of subtitiles (30 lines max) for translation later on and didn't get more Error nor warning mail till I reach the 25 times if GPT4 request cap for the last 3hr, whether pressing the  [⏩] Continue Botton or not.

I'll keep reporting situation here if I got anymore Error or Warning mails.

Thanks @4as for helping.

**Comment by latuh** [comment]
I'm looking forward to use this extension, has anything been reported related to the emails and uBlock Origin?

**Comment by 4as** [comment]
A quick reminder if anyone else is reading this: issues are not for discussion. If you have been banned while using DeMod please post information that could help me narrow down the reason. Anything else is considered off-topic for this issue.

**Comment by Lefioty** [comment]
I got another warning mail in Android phone environment (Kiwi Browser +  tampermonkey extension and DeMod script only as well). The warning mail time may just sent after I pressed "regenerate" button (accidentally Double pressed maybe?).

Again can't be sure exactly what triggered this warning mail due to I can't check out the debugging messages on Android phone. 

I'll keep reporting if I encounter anymore warning mails.

**Comment by 4as** [comment]
Thank you for taking time to investigate this. Double pressing could be an interesting case to study. DeMod is definitely intercepting standard regeneration requests, but perhaps there's an issue with how multiple requests in short time span are handled.
Warning emails usually take around a day to arrive, so it could be anything that you've done for the past 24 hours. But that being said, try not to double-press anything for the next few days, then if no emails arrive try meshing the regenerate button, and see if that will cause a warning to appear.

**Comment by Lefioty** [comment]
Ok, I got another warning mail again this time. I've waited for over 24hrs without any usage. And I think this is because this conversation is way too long. And it response pretty slow everytime I sent out request, over about 5~10 seconds then the output UI can show up correctly and streaming the outputs. Last time I got warning mail is in same conversation as well (I am developing a pretty long NSFW storyline in this conversation).

Didn't get any weird error message this time in Firefox this time. No double pressing or some sort. The only weired thing is the delayed output UI rendering. (Firefox warning message each time I send out requests: WEBGL_debug_renderer_info is deprecated in Firefox and will be removed. Please use RENDERER.)

So I'm worries about it's "long conversation" or at least "flagged accounts" might be "special cared" by the server side.

I may try another new account next month.

I've clear all cache data and browsing histories of firefox and test if it's the issue of caches causing delayed UI rendering.

I'll keep reporting if I encounter anymore warning mails.

**Comment by 4as** [comment]
Perhaps GPT-4 has different ways of checking the messages that DeMod doesn't block?  
If you're willing to spend more time on this, could you check if can get a warning for a conversation on GPT-3.5? As in, start a new NSFW conversation and see if DeMod works  (nothing gets flagged and you do not use anything out of the ordinary) but you still get an email from OpenAI.

**Comment by Vicarious789** [comment]
https://gyazo.com/0661eb676cc18a541665f463ed857b9c

This was once again with the secondary account I had the issue with before. This time I sent a prompt before getting the violation warning but it was literally instant when I hit enter. I was also using 3.5 for this prompt and I have used the same start prompt without issue multiple times in the last week. I'm not sure what the errors mean exactly or if I have had the same ones before, this is the first time I checked.

I have never been banned despite multiple warnings in the past and originally I got warnings like a month after I started using your script which I assumed was from my blatant violations before that. These last few weeks is the first time I have noticed an instant automatic trigger which makes me think they changed something about how they issue warnings if nothing else.

**Comment by Lefioty** [comment]
> Perhaps GPT-4 has different ways of checking the messages that DeMod doesn't block? If you're willing to spend more time on this, could you check if can get a warning for a conversation on GPT-3.5? As in, start a new NSFW conversation and see if DeMod works (nothing gets flagged and you do not use anything out of the ordinary) but you still get an email from OpenAI.

Got it. I'll test it in days or two. TTBH GPT-3.5 have became harder to trick for generating NSFW stuff recently which response more "refused" messages than before (DeMod still working perfectly while my last tests of GPT-3.5 about 3 weeks ago). I'll report the result and debug messages if I got more warning mails during the test.

BTW, There are Errors like "Content-Security-Policy: ... " by DeMod "just while chatGPT site is loaded before opening any conversations", or when I click the GPT-4 model before starting another new converasation on my Firefox debug console (which means DeMod is working correctly). These Errors usually apear "after" the request. I can still using chatGPT as usaual tho. I don't know is that means my account is flagged, or it just detected NSFW contents in the coversation list (and should show up warning messages if I didn't using DeMod)?

**Comment by 4as** [comment]
Since moderation can no longer be prevent, users that use DeMod need to be aware they can still be warned or even banned. 
It's no longer something that DeMod can prevent, thus I'm closing this issue.
