### ISSUE TITLE
Page Update

### ISSUE THREAD

**Issue by yo-minn** [4as/ChatGPT-DeMod#23]
In ongoing conversations, no warnings are displayed, but when switching threads or refreshing the page, warnings are displayed."

**Comment by 4as** [comment]
Yes, because after the latest update there is no way to prevent moderation now. I tried to make it clear on DeMod's main page.

**Comment by yo-minn** [comment]
I was able to understand it after reading through the previous threads
carefully. I apologize for the inconvenience caused
Thank you for your assistance and support. I have found it incredibly
helpful

2023年7月23日(日) 18:13 4as ***@***.***>:
