### ISSUE TITLE
The orange warning message is now on the right, pushing all the text in a tight space on the left

### ISSUE THREAD

**Issue by Nayko93** [4as/ChatGPT-DeMod#26]
The Orange censorship message is not placed UNDER the message anymore but instead on the right side, pushing all the text in a tight space on the left making it really ugly and annoying to read
When I write the message all is good, Demod works and block the orange flag from showing, but when I reload the page I get this...

https://www.reddit.com/r/ChatGPTNSFW/comments/15esd9c/wtf_anyone_have_the_same_problem_with_the/ 

A other weird thing is that with demod enabled, the orange flags are showing up again, the text become orange...  but even weirder the RED flags are becoming orange...

For now the only way I found to solve this is to use my  ad-blocker and block the little orange box directly, the text is still orange but at least the orange box doesn't push the text on the side

**Comment by 4as** [comment]
I just released an update that removes all signs of moderation, even if you refresh the page. Warning placement should no longer be an issue.

**Comment by pukkandan** [comment]
> I just released an update that removes all signs of moderation

Would you consider adding the warning or coloration back? I would prefer to know when a message is moderated and would like to block only the message removal.

**Comment by 4as** [comment]
You can just turn DeMod Off and refresh the conversation, you will see what was marked.  
Currently I can only either clear moderation results or leave them be - I can't change how the messages appear. So the choice is either to not have your message removed, or see the moderation and have your message removed, there is no in between.  
I'll see if I can find a way to display the moderation status in some other way, tho.
