### ISSUE TITLE
OpenAI ChatGPT - Content Policy Violation (Even with Demod Activated) 

### ISSUE THREAD

**Issue by aiden34221** [4as/ChatGPT-DeMod#27]
I received this warning 16 hours ago even with Demod. Anybody received this warning recently? 
![image](https://github.com/4as/ChatGPT-DeMod/assets/140358667/1257c985-d284-4212-857d-e0e75be92a30)

**Comment by aiden34221** [comment]
> 

Alright, thanks for the reply.

**Comment by 4as** [comment]
Like it says on DeMod's main page "Prevents removal, messages are still flagged."
