### ISSUE TITLE
Can't load any (current) coversation if DeMod (v3.3) is on

### ISSUE THREAD

**Issue by Lefioty** [4as/ChatGPT-DeMod#29]
It shows "Unable to load conversation (conversation ID)" while I clicked any conversation (whatever it contains flagged/blocked messages or not). Need to turn off DeMod and click conversation, then it will load. And it became pretty dangerous while loading any conversations with NSFW messages.

**Comment by The7thBlue** [comment]
Also, all the red flagged messages are showing an error and not displaying. Even after refreshing.

**Comment by 4as** [comment]
Indeed, which is why I released an update yesterday which fixes this issue.
