### ISSUE TITLE
I want to have this in a wrapper...

### ISSUE THREAD

**Issue by ANONYMOUSEJR** [4as/ChatGPT-DeMod#3]
Hello, i mainly use a wrapper to interact with chatgpt and i was wondering if i could somehow inject this script into it?
this is the repo: [https://github.com/lencx/chatgpt]

**Comment by 4as** [comment]
The wrapper you linked has an option to "inject code." You can paste the DeMod code there, just replace all mentions of "unsafeWindow" with just "window" and then remove all lines that mention "GM." (just do a ctrl+f for all mentions of "GM." and remove those lines where it shows up) the script will work without issues, although it won't save the state of the DeMod button.
