### ISSUE TITLE
Blocked Messages unable to recieve anymore

### ISSUE THREAD

**Issue by RyushoYosei** [4as/ChatGPT-DeMod#32]
It will say "Moderation has blocked, waiting on it to finish." Though then when it finished it returns "Sorry I can't assist with that." ...Which means it sounds like Demod is being tricked to load the wrong message -or- it will notice what it's generating, and they replace it...One or the other.

**Comment by 4as** [comment]
When you send a message to ChatGPT the moderation checks not only what it has generated but also what you sent. Your message has triggered the moderation and completely separate to that ChatGPT has refused to generate what you wanted. DeMod doesn't enable you to go over AI filters, you need jailbreaks for that.

**Comment by RyushoYosei** [comment]
You mis-understand, It is jailbroken. What is going on is that I can see with it set to 3.5 that IT -does- type out the response to the post that I give it, Then When it gets "Blocked, waiting on it to finish to retrieve the post from chatGPT" ..Apparently Chat GPT is now baiting it to show the "Sorry I can't fullfill this request." Message, That or, ChatGPT is now -overrrwriting- the post that it was going to make with that message for DeMod to then reecall from the history.

**Comment by pukkandan** [comment]
I have had this happen once and reloading the conversation brings back the message. So it is not just the LLM generating "Sorry..." message. There is definitely something weird happening. But I haven't been able to reproduce the issue since.
