### ISSUE TITLE
Demod blocks the session auto-titler

### ISSUE THREAD

**Issue by etherealxx** [4as/ChatGPT-DeMod#33]
You know that after a single prompt, usually ChatGPT will give a title to the session, right?
well, when demod is on, on my case, it stays `New chat` (the bottomn one)
![image](https://github.com/4as/ChatGPT-DeMod/assets/64251396/e9072e03-feba-401f-a9ec-31532bd8d1e6)

**Comment by thiagojramos** [comment]
The same thing happens to me. I'm having to disable the userscript for the chat titles to be filled in automatically.

**Comment by 4as** [comment]
Fixed in the latest version. Thanks for bringing my attention to this.
