### ISSUE TITLE
Just an FYI

### ISSUE THREAD

**Issue by OMGitsMatt45** [4as/ChatGPT-DeMod#35]
ChatGPT seems to have updated it's format and maybe some other things in preparation for 4 Turbo. I don't know if that has affected this at all. Just wanted to let you know.

**Comment by ValerieDD** [comment]
I concur. About 3:30 pm Eastern today (7 Nov) all was working as it had been for several days. Now it's a bit after 9pm on 7 Nov and I'm seeing orange content warnings on both my prompt and the response.  Both are displayed, but now with the added orange text etc.  FWIW the status indicator shows grey for me on the same page, so there is some disconnect between the DeMod indicator colors and the warning level on the prompt/response.  Hope it's an easy fix to keep up the cat-and-mouse game with OpenAI until something better comes along!

And thank you for any fixes you are able to come up with! DeMod is the only thing keeping me sane and still using chatGpt at this point ;)

**Comment by 4as** [comment]
Fixed in the new version. I can only access 3.5 but I suspect it will work for 4.0 too. I'll reopen the issue if it doesn't.
