### ISSUE TITLE
Error in Moderation

### ISSUE THREAD

**Issue by OMGitsMatt45** [4as/ChatGPT-DeMod#36]
I suddenly keep getting Error in Moderation messages when i try to submit new entries. I'll I did was try to set up some custom instructions, and they suddenly appeared. I turned them off and they still appeared. I don't know whats going on.

**Comment by OMGitsMatt45** [comment]
Nevermind i think they're having another ddos attack

**Comment by 4as** [comment]
Before you submit an issue for DeMod always make sure it's actually related to DeMod.
