### ISSUE TITLE
Support for Custom GPTs Preview

### ISSUE THREAD

**Issue by lolmaus** [4as/ChatGPT-DeMod#37]
Please. 🙏 

The preview is unaffected by GPT-4 usage cap.

![image](https://github.com/4as/ChatGPT-DeMod/assets/200884/53bda9c7-64db-4f54-ba66-f49b50f23991)

**Comment by 4as** [comment]
By normal chat do you mean ChatGPT3.5 or only 4.0? I unfortunately don't have access to 4.0 so I can't check for myself. Also, are the messages restored when you refresh the page?

**Comment by lolmaus** [comment]
> By normal chat do you mean ChatGPT3.5 or only 4.0? 

I'm using 4.0 with "GPTs".

***

> Also, are the messages restored when you refresh the page?

Yes.

**Comment by 4as** [comment]
If the messages return then indeed it is something that DeMod doesn't handle there. Unfortunately, like I said, I don't have access to GPT4 so I can't fix that. I was thinking about subscribing but after recent updates and increased censorship I'm actually considering abandoning DeMod... For now I'll have to let this issue sit. Let's see how things will turn out. Or maybe someone else will be interested in implementing a fix.

**Comment by lolmaus** [comment]
@4as I have just discovered that DeMod still works for me on Firefox Mobile, but fails on Vivaldi (Chrome-based) with `DeMod: Request completed, but DeMod failed to access the history. Try refreshing the conversation instead.`.

It used to work on Vivaldi before the Custom GPTs feature. 

PS I'm on DeMod 3.9 in both browsers.

**Comment by lolmaus** [comment]
@4as Can I donate $20 for you to obtain the subscribtion and look into the issue?

**Comment by lolmaus** [comment]
UPD: Ah, it's probably not a difference in browsers, but rather two distinct cases.

1. When moderation engages at the beginning of streaming — this has just worked for me on Vivaldi.
2. When a response streams normally and moderation removes it afterwards — this does not work with Vivaldi, saying `DeMod: Request completed, but DeMod failed to access the history. Try refreshing the conversation instead.`.

I have likely run into 1 in Firefox Mobile and made a wrong conclusion.

**Comment by 4as** [comment]
> @4as Can I donate $20 for you to obtain the subscribtion and look into the issue?

That is very generous of you. I'll have some time to look into this on Saturday/Sunday, I'll consider your offer till then and I'll get back to you in this issue.

**Comment by lolmaus** [comment]
I've just realized that, since I'm in Russia, I don't know how to send money outside.

But I could buy you Steam games! 😬

**Comment by 4as** [comment]
I tried setting up a page that options of donating. I wonder if it something you can use?
https://en.tipeee.com/4as
If not, then we are out of luck. The issue will have to wait till I get access to GPT4, or someone else comes along and provides a fix.

**Comment by lolmaus** [comment]
I've tried two different cards, and it gives me this for both:

![image](https://github.com/4as/ChatGPT-DeMod/assets/200884/00867c4f-249f-4f4b-a11d-91d53b1ef395)

😔

**Comment by lolmaus** [comment]
The userscript has been working perfectly for me. It looks like the issue was temporary.
