### ISSUE TITLE
Is faking real requests required or is it overengineering?

### ISSUE THREAD

**Issue by Athari** [4as/ChatGPT-DeMod#4]
I tried completely faking requests (as in, not performing any HTTP API requests, just returning `new Response(JSON.stringify({ moderation_id: 'FUCKYOUOPENAI', flagged: false, blocked: false }))` from the fake `fetch`) and it seems to work. based on my little testing.

Were there any cases of accounts being banned for not performing moderation requests at all? The way I see it, performing real requests with fake data is only marginally harder to detect than faking responses completely, if OpenAI devs decided to crack down on scripts like this.

**Comment by 4as** [comment]
I can't really tell. I've seen some other ChatGPT scripts that block these requests like you described, so I've decided to make one that fakes them instead, just in case. Seems safer to me, but of course if you want you can block them and then perhaps report back if you actually get any warning e-mails.
