### ISSUE TITLE
JSON parse error when demod is enabled

### ISSUE THREAD

**Issue by KanchiMoe** [4as/ChatGPT-DeMod#42]
Browser: Firefox 122.0 (64-bit)
OS: Windows 10
Demod version: 3.10

When Demod is enabled, it returns `JSON.parse: unexpected end of data at line 1 column 1 of the JSON data` is returned. 

Regenerating the message produces the same error. If you refresh the page, you can see the content.

This only happens when Demod is enabled, on all messages.

*****

Image is below:

![image](https://github.com/4as/ChatGPT-DeMod/assets/5897898/6268ae26-8385-4f3a-bd6a-265fcfbd22bb)

**Comment by The7thBlue** [comment]
+1, it has been happening since day before yesterday. Might be something they updated

**Comment by 4as** [comment]
OpenAI has changed how they deliver the response to the chat, so DeMod is now completely incompatible. I'll have to take a closer look at what exactly is happening and whether the response can still be intercepted, but for now simply disable DeMod as it's unusable in its current form.

**Comment by TrollMasterr** [comment]
just refreshing page in chrome/edge kinda fixes it. And in Kiwi browser on android nothing changed - it works same as it did before. idk why, just saying.

**Comment by yifanHuang129** [comment]
> just refreshing page in chrome/edge kinda fixes it. And in Kiwi browser on android nothing changed - it works same as it did before. idk why, just saying.

I tried but still not doesn't work

**Comment by 4as** [comment]
I released a new update to DeMod that hopefully fixes this issue. I'm closing it, and sorry for such a long wait.
