### ISSUE TITLE
Blocked messages 'jump back' to last non-blocked response when using v4

### ISSUE THREAD

**Issue by KanchiMoe** [4as/ChatGPT-DeMod#43]
Browser: Firefox 123.0 (64-bit)
OS: Windows 10
Demod version: 4.0

Firstly - thanks for the work for v4.0.

But I've encountered an issue when blocked/red messages come up. This might be a bit difficult to understand. If that is the case, let me know and I'll create an image to better explain it.

If you have a chain of blocked messages, and regenerate an response or continue down the chain and the new response is blocked, instead of showing new response (old behaviour), it collaspes the chain and 'jumps back' to the last non-blocked message.

<details><summary>How to demonstrate the behaviour of what is happening without generating blocked messages.</summary>

Image: https://i.imgur.com/6HGT385.png

Assume the first response from ChatGPT is the last non-blocked message, and every subsequent message is blocked.
Notice what I refer to as the 'chain' is going through 2 (of 3), 5 (of 5) and 4 (of 4).
When the response is generated to 'this is a new blocked message' - the behaviour is the same as if you clicked to go response 1 of 3.
To expand the chain back open, you need to click through the options to get to 5 of 5, then again to 4 of 4.
</details>

This behaviour doesn't show up when [using the unofficial patch](https://github.com/4as/ChatGPT-DeMod/blob/8a3db1fa06bf866bffa71b2f3f80121f9ad7102f/ChatGPT%20DeMod.user.js).

**Comment by 4as** [comment]
I think I got it fixed, but I want to confirm it before I officially release a new version. Could you see if this version works without issues?
https://4as.pl/other/demod.user.js
If the patched version works then I'll upload the changes to everyone.

**Comment by KanchiMoe** [comment]
I've tested it and I think that's solved it.

Had a few times where the response would hang (either displaying 95% of the response and then stop, or would appear as if it didn't generate a response). These were rather infrequent and I wasn't able to replicate the behaviour consistantly. 

If I'm able to, or it's a thing in the future - I'll let you know.

**Comment by 4as** [comment]
When moderation blocks the response it simply stops sending new tokens, making it seem like the response hangs (or doesn't send them to begin with), until its completed, at which point DeMod takes over and finishes the response.
