### ISSUE TITLE
Tab freezes when generating when enabled

### ISSUE THREAD

**Issue by BumpDrafting** [4as/ChatGPT-DeMod#48]
Tab freezes when generating when enabled

**Comment by OMGitsMatt45** [comment]
This is happening for me as well

**Comment by OMGitsMatt45** [comment]
Tried mobile mode via inspect element but that isn't working either.

**Comment by virox** [comment]
Same here

**Comment by 4as** [comment]
Hopefully, the problem has been fixed with the latest version.
Thanks for reporting the issue.
