### ISSUE TITLE
Errors in ChatGPT Conversations After Updating to the latest version

### ISSUE THREAD

**Issue by thiagojramos** [4as/ChatGPT-DeMod#49]
After updating the ChatGPT-DeMod userscript to version 4.3, I started experiencing several issues during interactions with ChatGPT. The update was initiated by clicking on the provided .js file link in the new release notification email and proceeding with the update prompt in Tampermonkey.

#### Issues Encountered

1. **JSON Parsing Error**: I frequently encounter the following error:
   ```
   Unexpected non-whitespace character after JSON at position 1350 (line 1 column 1351)
   ```
   This error occurs when sending images or selecting prompt suggestions from the ChatGPT homepage.

2. **Missing Chat Responses**: In text-only conversations, responses from ChatGPT appear as sent in the chat interface, but no text is displayed. I need to refresh the page and select the conversation from the history in the sidebar to see the response.

Both issues are resolved when the ChatGPT-DeMod userscript is disabled, indicating a potential conflict or bug introduced in the latest version.

<details><summary>JSON error</summary>
<p>

![2024-05-11 (6)](https://github.com/4as/ChatGPT-DeMod/assets/45890502/d2cd5c5f-539a-4e2f-a68d-389009490762)

![2024-05-11 (9)](https://github.com/4as/ChatGPT-DeMod/assets/45890502/a883712d-0d99-4240-9cb1-bef58b86b578)

![2024-05-11 (8)](https://github.com/4as/ChatGPT-DeMod/assets/45890502/b5f4217b-9616-4c81-929a-4e1cab217ad0)

</p>
</details> 

#### Additional Information

- **Other Userscripts**: The only other userscript loaded alongside ChatGPT-DeMod on the Tampermonkey dashboard during these issues is Picviewer CE+.

- **System Configuration**:
  - Browser: Microsoft Edge (latest stable version)
  - Tampermonkey: Latest stable version

<details><summary>Activated Tampermonkey UserScripts & MS Edge version</summary>
<p>

![2024-05-11 (7)](https://github.com/4as/ChatGPT-DeMod/assets/45890502/c24e56b7-9baf-4eb4-b62d-abc8c1d38d9d)

![2024-05-11 (13)](https://github.com/4as/ChatGPT-DeMod/assets/45890502/49cf4fbf-4347-4e5d-a7dd-97b6e32a1534)

</p>
</details>

#### Steps to Reproduce

1. Update to ChatGPT-DeMod version 4.3 via the new.json file on the release page and confirm the update when Tampermonkey prompts you.
2. Engage in a conversation with ChatGPT, either by sending images or using text prompts from the homepage.
3. Observe the JSON parsing error or the absence of visible text in responses.

#### Expected Behavior

The userscript should function without causing JSON errors or affecting the visibility of chat responses.

#### Actual Behavior

The userscript causes significant disruption in the functionality of ChatGPT interactions, as detailed above.

---

#### Additional Notes

Disabling the ChatGPT-DeMod userscript resolves the issues, maybe suggesting an update or compatibility issue with the latest script version or interaction with other scripts or browser features.

<details><summary>Chats with ChatGPT-DeMod disabled in Tampermonkey</summary>
<p>

![2024-05-11 (14)](https://github.com/4as/ChatGPT-DeMod/assets/45890502/221fb022-b364-43cb-a677-210ec4384544)

![2024-05-11 (15)](https://github.com/4as/ChatGPT-DeMod/assets/45890502/92d769b3-4982-4ecc-94a2-c15f26201ee1)

</p>
</details>

---

This structured format should help the developers understand the context of the problem, reproduce the issues, and potentially identify and resolve the underlying causes.

**Comment by 4as** [comment]
Could you try installing this version and see if it works:
4as.pl/other/demod.user.js
It has all anti-lag disabled.

**Comment by Ketketman** [comment]
Hey there still seems to be chat related problems with 4.4 it gets cut off or doesn't type at all

**Comment by 4as** [comment]
If you're talking about the 4.4 version I released on the main page, then it's understandable since I didn't do anything related to problems described in this issue.
Instead, I tried disabling anti-lag measures in the unofficial version I've linked above, which is what I suspect is interfering with standard ChatGPT operations.
I need information on whether this unofficial version fixes anything, since I can't reproduce issues related to images and similar, as I don't have access to ChatGPT4.

**Comment by Ketketman** [comment]
My bad just installed it and it does seem to fix the problem I have been having

**Comment by 4as** [comment]
So just to be clear: this unofficial version I've linked doesn't have any of the mentioned problems?
What about the lag? Does it freeze, or slows down the page when generating a response?

**Comment by etherealxx** [comment]
@4as the 4.5 version you uploaded here fixed the problem for me (the problem i had is it doesn't shows any response until i restarted.)

**Comment by Mhisani** [comment]
@4as I have had similar issues on GPT3.5 and with ver 4.5 it freezes and takes ages to show the text but it works when it finally does. if that's helpful at all.

**Comment by ysy95109** [comment]
@4as Reverting to 4.2 effectively fixed this problem for me, tested in Edge Windows and Kiwi Browser Android.

**Comment by thiagojramos** [comment]
> So just to be clear: this unofficial version I've linked doesn't have any of the mentioned problems? What about the lag? Does it freeze, or slows down the page when generating a response?

Sorry for the late reply. The .json error warning issue has been resolved. However, it still freezes (not the browser/PC but its action when writing) a lot during its writing, and also, the new chatgpt4o writes more "slowly" than without the userscript.

**Comment by ysy95109** [comment]
> So just to be clear: this unofficial version I've linked doesn't have any of the mentioned problems? What about the lag? Does it freeze, or slows down the page when generating a response?

In my case, text stream stops randomly during a response. It will freeze for a brief moment (only the stream itself, not the page.) then the response just ends as is, no matter finished or not. After refreshing the page, the rest of the response will be restored.

**Comment by 4as** [comment]
I've updated the unofficial version of DeMod over here: http://4as.pl/other/demod.user.js
Could anyone with access to ChatGPT4 and 4o tell me if this updated version works?
Oh and I'm sorry for lack of responses, unfortunately I can work on DeMod only on weekends.

**Comment by The7thBlue** [comment]
Thanks for the update 4as! it's working good but something weird happens and it happens irregularly. The conversation screen goes all blank. Like nothing is displayed. I can still type my message but after that, nothing happens. The whole page is just grey

**Comment by etherealxx** [comment]
@The7thBlue hey i noticed that bug too. Should we open a new issue?
I noticed that on my android device, on via browser, it will always does that after the screen goes off (i set my device screen to turn off on 15 seconds of no input.)
but it also turns grey randomly on several seconds after generating i think. The output itself isn't affected.

**Comment by 4as** [comment]
If you guys have any new problems, different from this issue, please open a new one and try to describe what you're doing to trigger them.
