### ISSUE TITLE
ChaptGPT-DeMod not working in Chrome or Edge

### ISSUE THREAD

**Issue by qwalpo99** [4as/ChatGPT-DeMod#50]
I just downloaded ChatGPT-DeMod for both Google Chrome and Microsoft Edge. But it doesn't seem to be working on either.

When I use it in Chrome, ChatGPT 3.5 simply writes nothing most of the time, and the few times it does write something, it stops part-way through.

When I use it in Edge, it always says "Unexpected non-whitespace character after JSON at position 1357 (line 1 column 1358)"
![2024-05-16](https://github.com/4as/ChatGPT-DeMod/assets/96638233/02d84890-8cb3-49de-8549-372024289ade)

What do I do?

**Comment by 4as** [comment]
Current latest version of DeMod just doesn't work.
It's the same problem as this issue: https://github.com/4as/ChatGPT-DeMod/issues/49
I'm going to close this one, so there is no duplication. Please follow the other issue instead.
