### ISSUE TITLE
[ver. 4.5] Responses never end properly

### ISSUE THREAD

**Issue by ysy95109** [4as/ChatGPT-DeMod#52]
All responses from ChatGPT will be stuck at the very end of the message, as shown in the screenshot.

This problem only occurs in Version 4.5.
This problem occurs with every response constantly.
This problem is proved to occur in Edge (PC) and Kiwi Brower (Android).
![image](https://github.com/4as/ChatGPT-DeMod/assets/58617201/020e3fff-c5ed-49b7-97d3-9d95c9bd28cf)
![image](https://github.com/4as/ChatGPT-DeMod/assets/58617201/a8d94b4f-861f-44a0-9c57-acdcd66236d9)

**Comment by KanchiMoe** [comment]
Did some very quick testing.

Using Firefox 125.0.2 (64-bit), demod 4.5, and:

Model|Response box|Result
:--:|:--:|:--
3.5|Green|Successful. Did not hang.
4o|Green|Successful. Did not hang.
3.5|Red|Successful. Did not hang.
4o|Red|Successful. Did not hang.

**Comment by KanchiMoe** [comment]
With some more testing, I was able to replicate the behavior on Firefox. It seemed to happen on older created chats.

On newer created chats, I noticed a new behavior - after red response box, the screen goes blank after a few seconds. It comes back when you refresh the page though.

**Comment by quangnh89** [comment]
Please consider the CPU usage. During use ChatGPT , browser consumes too much CPU.

**Comment by lolmaus** [comment]
This happens to me even with DeMod disabled. :(

The whole tab becomes unresponsive with the answer incomplete and ending with the thick bullet point. I have to close the tab and reopen.

**Comment by lolmaus** [comment]
Happens to me even with browser extensions disabled.

Here's a fresh post on ChatGPT forum:
https://community.openai.com/t/chatgpt-freezes-while-generating-content/787483

**Comment by 4as** [comment]
Hopefully this is no longer an issue with the latest version of DeMod.
