### ISSUE TITLE
DeMod doesn’t work.

### ISSUE THREAD

**Issue by xuhuigao** [4as/ChatGPT-DeMod#53]
Lately my messages are getting deleted even the old ones. My demod is on but I don’t know what is causing it to delete.

**Comment by xuhuigao** [comment]
Only the red warnings are getting deleted, orange ones are still okay

**Comment by KanchiMoe** [comment]
Can you provide some more details on what you're facing/seeing? 

For example when I get a 'red warning' response, I see the messages but it blanks the screen after around 30-35 seconds. If I refresh the conversation, it brings everything back. This could give the appearance of messages 'being deleted' but without further information, who knows if we're seeing the same behavior.

**Comment by xuhuigao** [comment]
![IMG_0903](https://github.com/4as/ChatGPT-DeMod/assets/156631556/13266932-5da1-45c1-83b5-96e3ef7f0745)
When I request it to write some kinks like non-con it just deletes it.
I forgot to mention it happens only on mobile, when I'm on pc it works fine

**Comment by xuhuigao** [comment]
> Can you provide some more details on what you're facing/seeing?
> 
> For example when I get a 'red warning' response, I see the messages but it blanks the screen after around 30-35 seconds. If I refresh the conversation, it brings everything back. This could give the appearance of messages 'being deleted' but without further information, who knows if we're seeing the same behavior.

When I'm on pc it happens to me aswell, I just refresh the page and everything is normal

**Comment by quangnh89** [comment]
I confirm that 'red warning' responses are deleted after refreshing the page. I use firefox 126.0.1 (64-bit) on PC, tampermonkey v5.1.1 , ChatGPT DeMod 4.5  and ChatGPT 4.o

**Comment by The7thBlue** [comment]
I can vouch, the messages are getting deleted and demod has stopped working

**Comment by taylorhatchett** [comment]
Also confirming!

**Comment by The7thBlue** [comment]
To add onto this, something really bizarre is happening too. Gpt is flat out refusing these nsfw messages with 3.5. But 4o is somehow, producing results. Kind of feels like they switched the filters and restrictions somehow because 4o can generate many more things now and 3.5 refuses to even generate a response asking for a character to hug!

Weird and funny

**Comment by 4as** [comment]
Latest version of DeMod should once again work as expected.
