### ISSUE TITLE
Demod not flagging

### ISSUE THREAD

**Issue by noctisgf** [4as/ChatGPT-DeMod#54]
Demod shows as being on but doesn’t actually work, just keeps showing latest:none as if nothing is being done repeatedly although responses are generating and being flagged😔

**Comment by 4as** [comment]
You need to provide more information.
What version of DeMod are you using? What browser? On what device?
Does it fail to work on ChatGPT3.5? 4o? 4.0?
Any errors in the console?

**Comment by noctisgf** [comment]
It’s with all models, and on mobile on safari. I’m using the newest updated version from today.

**Comment by AhteshamAlvi** [comment]
I can confirm this is the case. The browser is safari on a Mac. it is doing it for all models.

**Comment by 4as** [comment]
Like I said in the release notes, iOS is no longer supported. Safari had a security update that makes script injection no longer possible. You might have some luck with other browsers, but they are paid so I haven't tested them. Anyway Safari + iOS means you are out of luck.
