### ISSUE TITLE
Not working :( browser is safari, and is up to date 

### ISSUE THREAD

**Issue by ddowen** [4as/ChatGPT-DeMod#56]
I imported the script (last updated 2 weeks ago) and the UI shows, but it doesn’t do anything and keeps saying “none” while the client turns all the output into a red box

**Comment by KanchiMoe** [comment]
Can you provide some more information, such as

* What browser are you using, and what version?
* What device? Desktop? Phone?
* Which models? 3.5? 4o?

**Comment by ddowen** [comment]
Safari, mobile, iPhone SE third generation. Same happens in the desktop mode on safari. Sent from my iPhoneOn Jun 29, 2024, at 4:36 PM, KanchiMoe ***@***.***> wrote:﻿
Can you provide some more information, such as

What browser are you using, and what version?
What device? Desktop? Phone?
Which models? 3.5? 4o?

**Comment by KanchiMoe** [comment]
Based on [this comment by 4as (the maintainer) a week ago](https://github.com/4as/ChatGPT-DeMod/issues/55#issuecomment-2185162894), Safari isn't supported anymore. Not sure if this includes the mobile version, but I suspect it does.
