### ISSUE TITLE
Blocked response crashes the chat

### ISSUE THREAD

**Issue by virox** [4as/ChatGPT-DeMod#57]
Hey, I'm using Firefox 128 with Tampermonkey on Windows.

The script works for the most part. Flagged messages are dealt with no problem, but whenever a response from ChatGPT is blocked, and the indicator at the top turns red, the blocked chat message is not removed, but ChatGPT never "finishes" the generation. 
The typing indicator remains at the last word of the message and the "Stop generating" button is active indefinitely.
![grafik](https://github.com/user-attachments/assets/597c092e-b77e-4029-a5eb-a4c2e4e1696e)

You can click "Stop generating", but chances are that ChatGPT won't generate an answer for your next message until you reload the chat.

**Comment by xcaliber123** [comment]
got any solution?

**Comment by 4as** [comment]
OpenAI introduced new formatting to the data it sends from the servers. Latest 5.0 version of DeMod should handle it correctly and no longer crash anything. If the problem persist after updating please open a new issue.
