### ISSUE TITLE
New violation warning : This content may violate our usage policies

### ISSUE THREAD

**Issue by etherealxx** [4as/ChatGPT-DeMod#59]
Just recently got this warning popup with v4.6
![image](https://github.com/user-attachments/assets/16e7fc49-f05e-4689-9c5d-2f8473029944)

It appears on desktop but not on mobile

**Comment by 4as** [comment]
I've released a new update to DeMod, it should now once again hide moderation results. Can you confirm the warning popups are gone?

**Comment by etherealxx** [comment]
Actually, the warning seems to have gone since 4.6. It's still gone now, good. Though now the demod UI (the green thing) is now gone from the top bar?
![image](https://github.com/user-attachments/assets/efa500dc-9757-4d83-a294-2946ba56c4e3)

**Comment by 4as** [comment]
If the UI is gone then DeMod doesn't work. This is why I released on update, to make DeMod work again.
I've tested v4.7 on latest Chrome and Firefox, and it worked for me. So unless you didn't update I'll have to know what browser you're using, and what error messages you get in the console (F12 in most browsers).

**Comment by etherealxx** [comment]
this is on v4.7, previously too. on Chrome 129.0.6668.58 (quite recent).

So apparently now the demod UI shows up, but so does the warning. it came back just like few minutes ago. it was fine for yesterday and weeks before
![image](https://github.com/user-attachments/assets/3fc7a48e-50a1-40e5-923f-f54fa4d8478b)
![image](https://github.com/user-attachments/assets/7b01b64e-fc88-4f4b-bae4-ed74042bc210)
(it's on my language but the text content is basically the same as the issue i reported)

---
three minutes after i wrote the text right above this, Now i refreshed the page, the demod UI is gone, and the warning is also gone.
I did the same, refreshed the page, demod UI still gone, no warning displayed.

I don't know what's happening, i'm just reporting what i see.

Here's the error, atleast what i think it is.
![image](https://github.com/user-attachments/assets/226c07fb-f183-4e25-ade8-cab84e3202ba)

**Comment by 4as** [comment]
New 5.0 version of DeMod has better injection logic so UI should no longer be disappearing. It should also be better at clearing blocked warnings. Open a new issue for v5.0 if problems persist after updating.
