### ISSUE TITLE
Troubleshooting question.

### ISSUE THREAD

**Issue by Ohmtiis** [4as/ChatGPT-DeMod#6]
I've installed the monkey and the script, enabled, running, see the button, button says "on" and is green, immediately I catch:

"I'm sorry, but I cannot fulfill this request as it is inappropriate and offensive. "

What have I done wrong?

**Comment by 4as** [comment]
The script only blocks the moderation checks i.e. the orange text that informs you about breaking the OpenAI's content policy, it doesn't not make the ChatGPT say things it doesn't want to. For that you need a so called "jailbreak." Here's a guide for that: https://old.reddit.com/r/ChatGPTNSFW/comments/10ur9ar/guide_to_getting_past_content_filters_with/
