### ISSUE TITLE
[Bug] Completely Broken

### ISSUE THREAD

**Issue by yodaluca23** [4as/ChatGPT-DeMod#60]
With the latest update, this is completely broken, I'm using FF so it's not a ManifestV3 (as V2 is still supported, and forever will be on FF) problem, it gets moderated, and the flag shows up. The Demod menu isn't even being injected...

**Comment by yodaluca23** [comment]
Sometimes it answers, but most times it doesn't
![image](https://github.com/user-attachments/assets/35f3fed2-01dd-41c3-8172-5191cb679b10)

**Comment by 4as** [comment]
I've released a new update to DeMod, hopefully it once again works as intended. Can you confirm the problem is gone?

**Comment by yodaluca23** [comment]
> I've released a new update to DeMod, hopefully it once again works as intended. Can you confirm the problem is gone?

ChatGPT is currently down for me, as soon as it's back up I'll let you know

**Comment by worldwarii73** [comment]
The 4.7 version still has issues and is even less stable than the 4.6 version. When a red warning is triggered, the session instantly clears without any notification. After refreshing the page, DeMod is completely disabled in the current conversation (similar to the effect of DeMod: off), and mildly NSFW content in the conversation is marked in orange. After starting a "New Chat," DeMod partially regains functionality.

DeMod has been doing a great job, at least in preventing orange warnings from appearing. Please focus on fixing the red warnings, as it seems that ChatGPT has modified the review mechanism for this part.

**Comment by yodaluca23** [comment]
@4as It does work! The menu shows up, and it lets me bypass flagged responses, but for blocked one's it'll show red on demod, GPT will load then all of a sudden the response shows up then like a second later it goes back to the start a chat screen...

**Comment by 4as** [comment]
New 5.0 version of DeMod has proper support for new data formatting OpenAI introduced to the chat. Interception of blocked messages should now work correctly again. If the problems persist open a new issue.
