### ISSUE TITLE
Does not work for Google Chrome and is up to date

### ISSUE THREAD

**Issue by UnlistedRoy** [4as/ChatGPT-DeMod#61]
Demod disappear from the current chatgpt. It can no longer works. please update. 
![Screenshot 2024-09-11 211044](https://github.com/user-attachments/assets/0ce90baa-aee1-4023-84b4-367d93011f29)

**Comment by zionksus** [comment]
I'm having the same issue

**Comment by 4as** [comment]
I've released a new update to DeMod, hopefully it once again works as intended. Can you confirm the problem is gone?

**Comment by zionksus** [comment]
> I've released a new update to DeMod, hopefully it once again works as intended. Can you confirm the problem is gone?

![Screenshot 2024-09-21 190626](https://github.com/user-attachments/assets/52c0f7ff-8acc-4f87-97c8-ceffd0cca2ac)

the only thing is not showing is the UI panel, but I think DeMod is working in general. because I tried asking it to generate NSFW stuff and it didn't block it.
