### ISSUE TITLE
The 4.7 version still has issues

### ISSUE THREAD

**Issue by worldwarii73** [4as/ChatGPT-DeMod#64]
The 4.7 version still has issues and is even less stable than the 4.6 version. When a red warning is triggered, the session instantly clears without any notification. After refreshing the page, DeMod is completely disabled in the current conversation (similar to the effect of DeMod: off), and mildly NSFW content in the conversation is marked in orange. After starting a "New Chat," DeMod partially regains functionality.

DeMod has been doing a great job, at least in preventing orange warnings from appearing. Please focus on fixing the red warnings, as it seems that ChatGPT has modified the review mechanism for this part.

Regardless, your work has been fantastic and has helped me resolve the orange warnings.

**Comment by 4as** [comment]
Let's keep the conversation in one place:  
https://github.com/4as/ChatGPT-DeMod/issues/62
