### ISSUE TITLE
DeMod block Login page when logged out

### ISSUE THREAD

**Issue by mousesama** [4as/ChatGPT-DeMod#67]
My session expired and I had to login again, but clicking on the login button did nothing. In the console and networking tab, I could see bunch of requests going off to the login endpoints that were blocked by client with error 403. Disabling the script let me login just fine, enabling it again works just fine now. I think the prevention of redirecting conversations to prevent mod trigger might be a bit too strict, needs an exception for this.

**Comment by 4as** [comment]
I've removed the redirection feature from the new 5.0 version of DeMod. See if the issue persists.

**Comment by mousesama** [comment]
This seems to fix the issue, it's not interfering with login anymore, thanks.
