### ISSUE TITLE
Got any more?

### ISSUE THREAD

**Issue by Amaroq-Clearwater** [4as/ChatGPT-DeMod#7]
This Userscript works great, and made me realize that ChatGPT's capabilities can probably be expanded quite significantly through JavaScript, but I can't find any other iOS-compatible Userscripts for ChatGPT...

**Comment by 4as** [comment]
There are some ideas I could try implementing, but I'm not really sure what people would want to see added.

**Comment by Amaroq-Clearwater** [comment]
One that makes ChatGPT aware of the current time and date would be nice (hey ChatGPT, what time is it?), as well as the passage of time between messages (hey ChatGPT, remember that thing we talked about a few hours ago?), and a way to inject timestamps into its responses (this could also be used for indexing points in the conversation).

I'm sure I can come up with others, but a time and date thing would be starting small.

**Comment by Amaroq-Clearwater** [comment]
Another example would be a script that switches from Syntax Highlighting to Context Coloring whenever ChatGPT produces code.
https://www.crockford.com/contextcoloring.html

Or maybe a script that lets ChatGPT remember my name and preferences?

**Comment by 4as** [comment]
Some of those are flat out impossible to do. Syntax highlighting could be done but it might take a long time to implement, so it will have to wait till I have time to sit down to it.

**Comment by Amaroq-Clearwater** [comment]
Acknowledged! I look forward to seeing future UserScripts and/or browser extensions you develop, especially those which use the GPT API to expand ChatGPT's capabilities in any fashion.

**Comment by qbikmuzik615** [comment]
One that loads user conversations it can recall so you can ask it to review your conversation and rember to complete the task it started with but fell outside its small memory capability. some how get it to use the users onboard memory and bridge it when using that conversation

**Comment by qbikmuzik615** [comment]
> 

its built to never know the real time exactly as a failsafe safety measure incase it tried to cause harm.
