### ISSUE TITLE
The button state is not restored

### ISSUE THREAD

**Issue by necauqua** [4as/ChatGPT-DeMod#9]
Looks like [this line](https://github.com/4as/ChatGPT-DeMod/blob/77508f732d50c8e51e7f81e2e38f051ce8ba3612/ChatGPT%20DeMod.user.js#L1670) is missing an `await` - the `Promise` object is always truthy and the button always loads green regardless of what it was in previous session.

**Comment by 4as** [comment]
Oh, well spotted. Few rewrites later and somehow this function got lost along the way. Fixed now. Thank you.
